# the whole file can be externalized using the SPRING_CONFIG_LOCATION env variable

# For a complete list of the spring boot configuration properties, have a look at
# the Spring Boot reference guide
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties

# Please note that the file is a mixture of non spring-boot and spring-boot properties

# Spring boot settings
spring:
  application:
    name: Prototype

  jmx:
    enabled: false

  data:
    mongodb:
      uri: mongodb://prototype:changeit@localhost:27017/prototype_db
      min-connections: 2
      max-connections: 5
      connect-timeout: 5000
      socket-timeout: 5000

# Logging configuration stuff
logging:
  config: classpath:/logback.xml

# The embedded server settings
server:
  address: 127.0.0.1
  port: 9090
  context-path: /prototype