# --------------------------------------------------------------------------------------------------
#
# Integration test configuration overrides
#
# --------------------------------------------------------------------------------------------------

spring:
  profiles: integration-test
  data:
    mongodb:
      uri: mongodb://prototype:changeit@localhost:27017/prototype_db_integration_test

# --------------------------------------------------------------------------------------------------

# Scheduler configuration
scheduler:
  auto-start: false

# --------------------------------------------------------------------------------------------------