---

- name: "Update APT cache"
  apt:
    update_cache=yes

- name: "Install bash utilities"
  apt:
    name=htop
    state=present
  with_items:
    - htop
    - wget
    - curl
    - w3m
    - unzip
    - ntp

- name: "Install latest vim"
  apt:
    name=vim
    state=latest